<?php 
/******************************
Author: Radovan Jakus
Company: Pierre & Rady LLC
Date: 09/27/2022
Revision: 09/27/2022
Name: Radovan Jakus
Version: 1.0
Notes: Mapping Definition
******************************/

function initData(){

            $aInitData = array(
                //INIT VALUES
                'ProductID' => "",
                'CardStockID' => "",
                'ShippingMethod ' => "",
                'ShippingServiceCode' => "",
                'ShippingServiceType' => "",
                'ShippingServiceName' => "",
                'PAN' => "",
                'PANMasked' => "",
                'BIN' => "",
                'BINExtended' => "",
                'PANLast4' => "",
                'Track1' => "",
                'Track1Masked' => "",
                'Track2' => "",
                'Track2Masked' => "",
                'Track2_Chip' => "",
                'PSN' => "",
                'PINBlock' => "",
                'CVC2' => "",
                'ICVV' => "",
                'EmbName' => "",
                'CompanyName' => "",
                'FirstNameT1' => "",
                'LastNameT1' => "",
                'ExpDate_YYMM' => "",
                'ChipData' => "",
                'PANHashed_SHA1' => "",
                'PANHashed_SHA256' => "",
                'DataPrepProfile' => "",
                'BulkID' => "",
                'BulkCompany' => "",
                'BulkFullName' => "",
                'BulkAddress1' => "",
                'BulkAddress2' => "",
                'BulkCity' => "",
                'BulkState' => "",
                'BulkZIPCode' => "",
                'BulkZIPCodeAddon' => "",
                'BulkPostalCode' => "",
                'BulkCountry' => "",
                'FullName' => "",
                'Address1' => "",
                'Address2' => "",
                'City' => "",
                'State' => "",
                'ZIPCode' => "",
                'ZIPCodeAddon' => "",
                'Country' => "",
                'FromFullName' => "",
                'FromAddress1' => "",
                'FromAddress2' => "",
                'FromCity' => "",
                'FromState' => "",
                'FromCountry' => "",
                'FromZIPCode' => "",
                'ServiceType' => "",
                'PackageType' => "",
                'WeightOz' => "",
                'ShipDate' => "",
                'ImageType' => "",
                'Reference1' => "",
                'Reference2' => "",
                'Reference3' => "",
                'Reference4' => "",
                'DataMatching' => "",
                'ValidFrom' => "",
                'MemberSince' => "",
                'DDAAccount' => "",
                'Currency' => "",
                'ImageIDFront' => "",
                'ImageIDBack' => "",
                'ExternalCardID' => "",
                'ExternalCHID' => "",
                'AdditionalField1' => "",
                'AdditionalField2' => "",
                'AdditionalField3' => "",
                'AdditionalField4' => "",
                'AdditionalField5' => "",
                'AdditionalField6' => "",
                'AdditionalField7' => "",
                'AdditionalField8' => "",
                'RecipientEmailAddress' => "",
                'RecipientPhoneNumber' => "",
                'FEDEXAccountNumber' => "",
                'Token' => "",
                'FileDate' => "",
                'FileName' => "",
                'CurrentDate' => "",
                'CardType' => "",
                'PostalCode' => "",
                'EmbName2' => "",
                'TrackingNumber' => "",
                'NumberOfRecordsInFile' => "",
                'NumberOfRecordsPerGrouping' => "",
                'NoErrorRecs' => "",
                'Status' => "",
                'iNoErrorRecs' => 0,
                'ErrorMessage' => "",
                'ErrorCode' => "",
                'ErrorDescription' => "",
                'Facility' => "",
                'HasError' => false,
                'ProductName' => "",
                'Customer' => "",
                'Barcode' => "",
                'NumberOfGoodRecordsInFile' => 0, 
                'NumberOfBadRecordsInFile' => 0,
                'NumberOfRecordsTAGUS' => 0,
                'NumberOfRecordsTAGPL' => 0,
                'Processor' => "",
            );

            return $aInitData;
        }
        

?>